<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Analisa_model extends CI_Model
{

    public $table = 'analisa';
    public $id = 'id_analisa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('address ad', 'ad.id_add = an.id_add');
        return $this->db->get('analisa an')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_analisa', $q);
	$this->db->or_like('id_nama_tempat', $q);
	$this->db->or_like('rb', $q);
	$this->db->or_like('lk', $q);
	$this->db->or_like('ga', $q);
	$this->db->or_like('max', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_analisa', $q);
	$this->db->or_like('id_nama_tempat', $q);
	$this->db->or_like('rb', $q);
	$this->db->or_like('lk', $q);
	$this->db->or_like('ga', $q);
	$this->db->or_like('max', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


        public function rawan()
    {
       
     $data = $this->db->query(" select * from analisa  join address on address.id_add=analisa.id_add
join geocoding on geocoding.id_add=address.id_add


        where max =
      (select max(max) from analisa) and (select min(max) from analisa )");
     return $data;
}

    public function avgs()
    {


        
   $data = $this->db->query("select * from analisa  join address on address.id_add=analisa.id_add
join geocoding on geocoding.id_add=address.id_add

      where max = 
    (select floor(avg(max)) as data from analisa) ");
     return $data;
}




    public function aman()
    {


   $data = $this->db->query("select * from analisa  join address on address.id_add=analisa.id_add
join geocoding on geocoding.id_add=address.id_add


    where max 
        = (select min(max) from analisa )");


     return $data;

}

}

/* End of file Analisa_model.php */
/* Location: ./application/models/Analisa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-08-19 03:30:26 */
/* http://harviacode.com */